// Auto-generated manifest for gallery images and videos
// Dimensions and orientation filled from provided data

export const galleryManifest = [
  // Images
  { src: "/images/gallery/Hackacthon_Celtiis_2024_2.jpg", alt: "Hackacthon_Celtiis_2024_2.jpg", type: "image", width: 960, height: 1280, orientation: "vertical" },
  { src: "/images/gallery/Hackacthon_Celtiis_2024_3.jpg", alt: "Hackacthon_Celtiis_2024_3.jpg", type: "image", width: 960, height: 1280, orientation: "vertical" },
  { src: "/images/gallery/Hackacthon_Celtiis_2024_4.jpg", alt: "Hackacthon_Celtiis_2024_4.jpg", type: "image", width: 960, height: 1280, orientation: "vertical" },
  { src: "/images/gallery/Hackacthon_Celtiis_2024_5.jpg", alt: "Hackacthon_Celtiis_2024_5.jpg", type: "image", width: 720, height: 1280, orientation: "vertical" },
  { src: "/images/gallery/Hackacthon_Celtiis_2024_6.jpg", alt: "Hackacthon_Celtiis_2024_6.jpg", type: "image", width: 720, height: 1280, orientation: "vertical" },
  { src: "/images/gallery/Hackacthon_Celtiis_2024_7.jpg", alt: "Hackacthon_Celtiis_2024_7.jpg", type: "image", width: 1280, height: 960, orientation: "horizontal" },
  { src: "/images/gallery/horizontal-1.jpg", alt: "horizontal-1.jpg", type: "image", width: 960, height: 540, orientation: "horizontal" },
  { src: "/images/gallery/horizontal-2.jpg", alt: "horizontal-2.jpg", type: "image", width: 960, height: 540, orientation: "horizontal" },
  { src: "/images/gallery/horizontal-3.jpg", alt: "horizontal-3.jpg", type: "image", width: 960, height: 540, orientation: "horizontal" },
  { src: "/images/gallery/horizontal-4.jpg", alt: "horizontal-4.jpg", type: "image", width: 960, height: 540, orientation: "horizontal" },
  { src: "/images/gallery/JCI_10.jpg", alt: "JCI_10.jpg", type: "image", width: 6084, height: 3862, orientation: "horizontal" },
  { src: "/images/gallery/JCI_11.jpg", alt: "JCI_11.jpg", type: "image", width: 6084, height: 3862, orientation: "horizontal" },
  { src: "/images/gallery/JCI_12.jpg", alt: "JCI_12.jpg", type: "image", width: 6084, height: 3862, orientation: "horizontal" },
  { src: "/images/gallery/JCI_13.jpg", alt: "JCI_13.jpg", type: "image", width: 6084, height: 3862, orientation: "horizontal" },
  { src: "/images/gallery/JCI_14.jpg", alt: "JCI_14.jpg", type: "image", width: 6084, height: 3862, orientation: "horizontal" },
  { src: "/images/gallery/JCI_15.jpg", alt: "JCI_15.jpg", type: "image", width: 6084, height: 3862, orientation: "horizontal" },
  { src: "/images/gallery/JCI_16.jpg", alt: "JCI_16.jpg", type: "image", width: 5985, height: 3453, orientation: "horizontal" },
  { src: "/images/gallery/JCI_17.jpg", alt: "JCI_17.jpg", type: "image", width: 3596, height: 4828, orientation: "vertical" },
  { src: "/images/gallery/JCI_1.jpg", alt: "JCI_1.jpg", type: "image", width: 3699, height: 2466, orientation: "horizontal" },
  { src: "/images/gallery/JCI_2.jpg", alt: "JCI_2.jpg", type: "image", width: 4895, height: 3263, orientation: "horizontal" },
  { src: "/images/gallery/JCI_3.jpg", alt: "JCI_3.jpg", type: "image", width: 4895, height: 3263, orientation: "horizontal" },
  { src: "/images/gallery/JCI_4.jpg", alt: "JCI_4.jpg", type: "image", width: 5304, height: 3536, orientation: "horizontal" },
  { src: "/images/gallery/JCI_5.jpg", alt: "JCI_5.jpg", type: "image", width: 5304, height: 3536, orientation: "horizontal" },
  { src: "/images/gallery/JCI_6.jpg", alt: "JCI_6.jpg", type: "image", width: 5304, height: 3536, orientation: "horizontal" },
  { src: "/images/gallery/JCI_7.jpg", alt: "JCI_7.jpg", type: "image", width: 5898, height: 3862, orientation: "horizontal" },
  { src: "/images/gallery/JCI_8.jpg", alt: "JCI_8.jpg", type: "image", width: 5315, height: 3862, orientation: "horizontal" },
  { src: "/images/gallery/JCI_9.jpg", alt: "JCI_9.jpg", type: "image", width: 6084, height: 3862, orientation: "horizontal" },
  { src: "/images/gallery/vertical-1.jpg", alt: "vertical-1.jpg", type: "image", width: 720, height: 960, orientation: "vertical" },
  { src: "/images/gallery/vertical-2.jpg", alt: "vertical-2.jpg", type: "image", width: 720, height: 960, orientation: "vertical" },
  { src: "/images/gallery/vertical-3.jpg", alt: "vertical-3.jpg", type: "image", width: 720, height: 960, orientation: "vertical" },
  { src: "/images/gallery/vertical-4.jpg", alt: "vertical-4.jpg", type: "image", width: 720, height: 960, orientation: "vertical" },
  // Videos
  { src: "/images/gallery/Hackacthon_Celtiis_2024_1.mp4", alt: "Hackacthon_Celtiis_2024_1.mp4", type: "video", width: 1920, height: 864, orientation: "horizontal" },
  { src: "/images/gallery/Hackacthon_Celtiis_2024_10.mp4", alt: "Hackacthon_Celtiis_2024_10.mp4", type: "video", width: 464, height: 848, orientation: "vertical" },
  { src: "/images/gallery/Hackacthon_Celtiis_2024_11.mp4", alt: "Hackacthon_Celtiis_2024_11.mp4", type: "video", width: 848, height: 464, orientation: "horizontal" },
  { src: "/images/gallery/Hackacthon_Celtiis_2024_8.mp4", alt: "Hackacthon_Celtiis_2024_8.mp4", type: "video", width: 464, height: 848, orientation: "vertical" },
  { src: "/images/gallery/Hackacthon_Celtiis_2024_9.mp4", alt: "Hackacthon_Celtiis_2024_9.mp4", type: "video", width: 464, height: 848, orientation: "vertical" },
];
